This example showcases, how user can provide imput in SI units.

In [1]:
from py_files.data_prep import *
from py_files.data_utils import *
from py_files.mainframe import *
from py_files.data_example import *
import matplotlib.pyplot as plt

In [2]:
user_array = user_table_example()[3:]
properties_table_raw = properties_table_example()

In [3]:
for i, unit in enumerate(['imperial', 'si']):
    print(unit)
    print('-'*10)
    print(user_array[i], '\n')

imperial
----------
[[4.000e+00 3.800e+00 5.000e-01 8.310e+02]
 [3.000e+00 2.800e+00 5.000e-01 2.727e+03]
 [2.000e+00 1.800e+00 5.000e-01 2.070e+02]]

si
----------
[[4.00e+00 3.80e+00 5.00e-01 2.53e+02]
 [3.00e+00 2.80e+00 5.00e-01 8.31e+02]
 [2.00e+00 1.80e+00 5.00e-01 6.30e+01]]

In [4]:
for i, unit in enumerate(['imperial', 'si']):
    print(unit)
    print('-'*10)
    print(properties_table_raw[i], '\n')

imperial
----------
inlet_temperature          1800.000
ambient_temperature          68.000
h_fluid_to_pipe              60.000
k_pipe                        9.700
k_insulation                  0.025
mass_flow_rate            24155.000
specific_heat_capacity        1.000
solar_flux                   50.000
emissivity                    1.000
dtype: float64

si
----------
inlet_temperature           982.000
ambient_temperature          20.000
h_fluid_to_pipe             340.000
k_pipe                       16.800
k_insulation                  0.043
mass_flow_rate            10942.000
specific_heat_capacity        4.200
solar_flux                  157.700
emissivity                    1.000
dtype: float64

In [5]:
user_table = []
properties_table = []
for i, unit in enumerate(['imperial', 'si']):

    user_table.append(
        user_table_prepare(
            pd.DataFrame(user_array[i]),
            unit
        )
    )

    properties_table.append(
        prop_table_units_handler(
            pd.DataFrame(properties_table_raw[i]),
            unit
        )
    )

In [6]:
imperial = calculate_total_piping(Piping_Segment, Air, user_table[0], properties_table[0])
si = calculate_total_piping(Piping_Segment, Air, user_table[1], properties_table[1])

results_imperial = final_table_units_handler(imperial, 'imperial')
results_si = final_table_units_handler(si, 'si')

In [7]:
results_imperial

,Segment Length [ft],Temperature Inlet [F],Temperature Outlet [F],Surface Temperature Inlet [F],Surface Temperature Outlet [F],Heat Transfer Total [BTU/h.ft],Heat Transfer by Radiation [BTU/h.ft],Heat Transfer by Convection [BTU/h.ft]
0,831.0,1800.00,1767.09,315.46,312.08,1021.48,626.49,394.99
1,2727.0,1767.09,1686.32,305.86,297.59,767.04,461.17,305.87
2,207.0,1686.32,1682.08,287.40,286.98,533.51,313.68,219.83

In [8]:
results_si

,Segment Length [m],Temperature Inlet [C],Temperature Outlet [C],Surface Temperature Inlet [C],Surface Temperature Outlet [C],Heat Transfer Total [W/m],Heat Transfer by Radiation [W/m],Heat Transfer by Convection [W/m]
0,253.0,982.00,963.88,156.94,155.08,976.61,598.59,378.01
1,831.0,963.88,919.36,151.63,147.09,733.57,440.80,292.76
2,63.0,919.36,917.02,141.44,141.21,510.33,299.89,210.44